name: Build with Sonarcloud, for CI, and deploy to Google Cloud, for CD
on:
  push:
    branches:
      - main
      - release
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify -P all-tests --file drinkup/pom.xml org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Deploy to App Engine (Google Cloud)
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: drinkup/app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: false
          version: v1
      # - name: Deploy to google cloud with cloud build
      #   uses: CamiloGarciaLaRotta/watermelon-http-client@v1
      #   with:
      #     #url: https://cloudbuild.googleapis.com/v1/projects/${{ secrets.PROJECT_NAME }}/triggers/${{ secrets.TRIGGER_NAME }}:webhook?key=${{ secrets.GOOGLE_API_KEY }}&secret=${{ secrets.GOOGLE_SECRET }}
      #     url: ${{ secrets.GOOGLE_WEBHOOK_URL }}
      #     method: post
      #     data: '{}'

